---
dist: trusty
sudo: required

matrix:
  fast_finish: true

services:
  - docker

cache:
  docker: true

before_install:
  - docker build -t naftulikay/centos-vm:7 ./

install: true

script:
  - /bin/true

notifications:
  email:
    on_success: never
    on_failure: never
